_wandb:
    value:
        cli_version: 0.27.2
        e:
            g0rcjfn9hl0pcdfirlbnubzp0gbtkpch:
                codePath: src/tuning.py
                codePathLocal: src/tuning.py
                email: alihussnain1919@gmail.com
                executable: /Users/macbookair/steam_recommender/.venv/bin/python
                host: MacBookAir.fritz.box
                os: macOS-26.5.1-arm64-arm-64bit
                program: /Users/macbookair/steam_recommender/src/tuning.py
                python: CPython 3.12.4
                root: /Users/macbookair/steam_recommender
                startedAt: "2026-06-22T15:05:11.455637Z"
                writerId: g0rcjfn9hl0pcdfirlbnubzp0gbtkpch
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 5
                - 35
                - 53
            "2":
                - 5
                - 35
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.4
            "5": 0.27.2
            "10":
                - 20
            "12": 0.27.2
            "13": darwin-arm64
numeric_weight:
    value: 0.39192217889440484
text_weight:
    value: 0.6080778211055952
